<div>
    <div class="col-xxl-6">
        <div class="card">
            <div class="card-header align-items-center d-flex">
                <h4 class="card-title mb-0 flex-grow-1">افزودن ارز</h4>

            </div><!-- end card header -->

            <div class="card-body">
                <p class="text-muted">
                    لطفا در انتخاب خود دقت کنید
                </p>
                <div class="live-preview">
                    <form wire:submit="submit(Object.fromEntries(new FormData($event.target)))">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="coingeckoId" class="form-label">CoinGecko ID:</label>
                                    <input type="text" wire:model="coingeckoId" name="coingeckoId" class="form-control"
                                           placeholder="مثلا:bitcoin" id="coingeckoId">
                                    @error('coingeckoId') <span
                                        class="text-danger text-sm">{{ $message }}</span> @enderror
                                </div>
                            </div>
                            <!--end col-->
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="nameFa" class="form-label">نام ارز به فارسی:</label>
                                    <input type="text" wire:model="nameFa" name="nameFa" class="form-control"
                                           placeholder="مانند : بیت کوین" id="nameFa">
                                    @error('nameFa') <span class="text-danger text-sm">{{ $message }}</span> @enderror

                                </div>
                            </div>
                            <!--end col-->

                            <div class="col-lg-12">
                                <div class="text-end">
                                    <button type="submit" class="btn btn-success">
                                        <span wire:loading.remove>افزودن</span>
                                        <span wire:loading="">

                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="30" height="30"
                                                 style="shape-rendering: auto; display: block; background: transparent;" xmlns:xlink="http://www.w3.org/1999/xlink"><g><circle
                                                        stroke-linecap="round" fill="none" stroke-dasharray="50.26548245743669 50.26548245743669" stroke="#ffffff"
                                                        stroke-width="8" r="32" cy="50" cx="50">
                                              <animateTransform values="0 50 50;360 50 50" keyTimes="0;1" dur="0.6097560975609756s" repeatCount="indefinite"
                                                                type="rotate" attributeName="transform"></animateTransform>
                                            </circle><g></g></g><!-- [ldio] generated by https://loading.io -->
                                            </svg>
                                        </span>
                                    </button>
                                </div>
                            </div>
                            <!--end col-->
                        </div>
                        <!--end row-->
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title mb-0">لیست رمز ارزها</h5>
                </div>
                <div class="card-body">
                    <div id="alternative-pagination_wrapper" class="dataTables_wrapper dt-bootstrap5 no-footer">
                        <div class="row">
                            <div class="col-sm-12 col-md-6">
                                <div id="alternative-pagination_filter" class="dataTables_filter"><label>جستجو:<input
                                            wire:model.live="search"
                                            type="search" class="form-control " placeholder="مثال:بیت کوین یا bitcoin"
                                            aria-controls="alternative-pagination"></label></div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="alternative-pagination"
                                       class="table nowrap dt-responsive align-middle table-hover table-bordered dataTable no-footer dtr-inline"
                                       style="width: 100%;" aria-describedby="alternative-pagination_info">
                                    <thead>
                                    <tr>
                                        <th tabindex="0"
                                            aria-controls="alternative-pagination" rowspan="1" colspan="1"
                                            style="width: 110.722px;">ردیف
                                        </th>
                                        <th tabindex="0" aria-controls="alternative-pagination"
                                            rowspan="1" colspan="1" style="width: 183.661px;">ارز
                                        </th>

                                        <th tabindex="0" aria-controls="alternative-pagination"
                                            rowspan="1" colspan="1" style="width: 148.661px;">اقدام
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    @forelse($cryptos as $crypto)
                                        <tr class="odd">
                                            <td class="dtr-control" tabindex="0">
                                                {{$loop->iteration + $cryptos->firstItem() - 1}}
                                            </td>
                                            <td>
                                                <div class="d-flex align-items-center fw-medium">
                                                    <img src="{{$crypto->image_url}}" alt="{{ $crypto->name_en }}"
                                                         class="avatar-xxs me-2">
                                                    <a href="javascript:void(0);"
                                                       class="currency_name">{{ $crypto->name_fa }}
                                                        ({{ $crypto->name_en }})</a>
                                                </div>
                                            </td>

                                            <td>
                                                <button
                                                    wire:confirm="آیا از انتخاب خود برای حدف ارز اطمینان دارید؟"

                                                    wire:click="delete({{$crypto->id}})"
                                                    class="btn btn-sm btn-soft-danger">
                                                    <i class=" ri-delete-bin-6-line"></i>
                                                    حذف
                                                </button>
                                            </td>
                                        </tr>

                                    @empty
                                        <tr class="noresult" style="display: block;">
                                            <div class="text-center">
                                                <lord-icon src="https://cdn.lordicon.com/msoeawqm.json" trigger="loop"
                                                           colors="primary:#121331,secondary:#08a88a"
                                                           style="width:75px;height:75px"></lord-icon>
                                                <h5 class="mt-2">متاسفم! هیچ نتیجه ای یافت نشد</h5>

                                            </div>
                                        </tr>
                                    @endforelse
                                    </tbody>
                                </table>
                                <div class="noresult" style="display: none">
                                    <div class="text-center">
                                        <lord-icon src="https://cdn.lordicon.com/msoeawqm.json" trigger="loop"
                                                   colors="primary:#121331,secondary:#08a88a"
                                                   style="width:75px;height:75px"></lord-icon>
                                        <h5 class="mt-2">متاسفم! هیچ نتیجه ای یافت نشد</h5>
                                        <p class="text-muted mb-0">ما همه ارز را جستجو کرده ایم، هیچ ارزی برای
                                            جستجوی شما پیدا نکردیم.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 col-md-5">
                                <div class="dataTables_info" id="alternative-pagination_info" role="status"
                                     aria-live="polite">
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-7">
                                {{$cryptos->links('layouts.admin.pagination')}}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--end col-->
    </div>
</div>
